// <auto-generated />
using System;
using MapaMensal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MapaMensal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622155224_AddContasPessoais")]
    partial class AddContasPessoais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MapaMensal.Models.AppConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "IvaRate",
                            Value = "0.23"
                        });
                });

            modelBuilder.Entity("MapaMensal.Models.ContaPessoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GrupoRecorrencia")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pago")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecorrenciaAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRecorrencias")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValorPago")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorPrevisto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContasPessoais");
                });

            modelBuilder.Entity("MapaMensal.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("MapaMensal.Models.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNational")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2026, 6, 4),
                            IsNational = true,
                            Name = "Corpo de Deus"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2026, 6, 10),
                            IsNational = true,
                            Name = "Dia de Portugal"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2026, 8, 15),
                            IsNational = true,
                            Name = "Assunção de Nossa Senhora"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2026, 10, 5),
                            IsNational = true,
                            Name = "Implantação da República"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2026, 11, 1),
                            IsNational = true,
                            Name = "Todos os Santos"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2026, 12, 1),
                            IsNational = true,
                            Name = "Restauração da Independência"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2026, 12, 8),
                            IsNational = true,
                            Name = "Imaculada Conceição"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2026, 12, 25),
                            IsNational = true,
                            Name = "Natal"
                        });
                });

            modelBuilder.Entity("MapaMensal.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Client")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailyRate = 220m,
                            IsActive = true,
                            Name = "KCSIT/FNAC",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            DailyRate = 242m,
                            IsActive = true,
                            Name = "CLOSER/NB",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            DailyRate = 204m,
                            IsActive = true,
                            Name = "Capgemini/DPD",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("MapaMensal.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Arquivado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataEntrega")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasGastas")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("MapaMensal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MapaMensal.Models.WorkDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Mark")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Date")
                        .IsUnique();

                    b.ToTable("WorkDays");
                });

            modelBuilder.Entity("MapaMensal.Models.Tarefa", b =>
                {
                    b.HasOne("MapaMensal.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MapaMensal.Models.WorkDay", b =>
                {
                    b.HasOne("MapaMensal.Models.Project", "Project")
                        .WithMany("WorkDays")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MapaMensal.Models.Project", b =>
                {
                    b.Navigation("WorkDays");
                });
#pragma warning restore 612, 618
        }
    }
}
