// <auto-generated />
using System;
using MapaMensal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MapaMensal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629041141_CorECategoriaCompromisso")]
    partial class CorECategoriaCompromisso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MapaMensal.Models.AppConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("mapa_appconfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "IvaRate",
                            Value = "0.23"
                        });
                });

            modelBuilder.Entity("MapaMensal.Models.CategoriaCompromisso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("mapa_categorias_compromisso", (string)null);
                });

            modelBuilder.Entity("MapaMensal.Models.CategoriaContaPessoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("mapa_categorias_contas_pessoais", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "#5c6bc0",
                            Nome = "Habitação",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 2,
                            Cor = "#43a047",
                            Nome = "Alimentação",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 3,
                            Cor = "#fb8c00",
                            Nome = "Transporte",
                            Ordem = 3
                        },
                        new
                        {
                            Id = 4,
                            Cor = "#e53935",
                            Nome = "Saúde",
                            Ordem = 4
                        },
                        new
                        {
                            Id = 5,
                            Cor = "#8e24aa",
                            Nome = "Educação",
                            Ordem = 5
                        },
                        new
                        {
                            Id = 6,
                            Cor = "#00897b",
                            Nome = "Comunicações",
                            Ordem = 6
                        },
                        new
                        {
                            Id = 7,
                            Cor = "#f4511e",
                            Nome = "Lazer",
                            Ordem = 7
                        },
                        new
                        {
                            Id = 8,
                            Cor = "#039be5",
                            Nome = "Seguros",
                            Ordem = 8
                        },
                        new
                        {
                            Id = 9,
                            Cor = "#6d4c41",
                            Nome = "Assinaturas",
                            Ordem = 9
                        },
                        new
                        {
                            Id = 10,
                            Cor = "#757575",
                            Nome = "Outros",
                            Ordem = 10
                        });
                });

            modelBuilder.Entity("MapaMensal.Models.Compromisso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("ContaPessoalId")
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LinkOnline")
                        .HasColumnType("longtext");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("NotificarParticipantes")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Online")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RecorrenciaId")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ProjectId");

                    b.ToTable("mapa_compromissos", (string)null);
                });

            modelBuilder.Entity("MapaMensal.Models.CompromissoParticipante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aceite")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("AceiteEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CodigoPais")
                        .HasColumnType("longtext");

                    b.Property<int>("CompromissoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Notificar")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CompromissoId");

                    b.ToTable("mapa_compromisso_participantes", (string)null);
                });

            modelBuilder.Entity("MapaMensal.Models.ContaPessoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("GrupoRecorrencia")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Pago")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RecorrenciaAtual")
                        .HasColumnType("int");

                    b.Property<int>("TotalRecorrencias")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorPago")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorPrevisto")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("mapa_contas_pessoais", (string)null);
                });

            modelBuilder.Entity("MapaMensal.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("mapa_expenses", (string)null);
                });

            modelBuilder.Entity("MapaMensal.Models.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsNational")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("mapa_holidays", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2026, 6, 4),
                            IsNational = true,
                            Name = "Corpo de Deus"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2026, 6, 10),
                            IsNational = true,
                            Name = "Dia de Portugal"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2026, 8, 15),
                            IsNational = true,
                            Name = "Assunção de Nossa Senhora"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2026, 10, 5),
                            IsNational = true,
                            Name = "Implantação da República"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2026, 11, 1),
                            IsNational = true,
                            Name = "Todos os Santos"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2026, 12, 1),
                            IsNational = true,
                            Name = "Restauração da Independência"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2026, 12, 8),
                            IsNational = true,
                            Name = "Imaculada Conceição"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2026, 12, 25),
                            IsNational = true,
                            Name = "Natal"
                        });
                });

            modelBuilder.Entity("MapaMensal.Models.HorarioDisponivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<int>("DuracaoSlotMinutos")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("mapa_horarios_disponiveis", (string)null);
                });

            modelBuilder.Entity("MapaMensal.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Client")
                        .HasColumnType("longtext");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("mapa_projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailyRate = 220m,
                            IsActive = true,
                            Name = "KCSIT/FNAC",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            DailyRate = 242m,
                            IsActive = true,
                            Name = "CLOSER/NB",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            DailyRate = 204m,
                            IsActive = true,
                            Name = "Capgemini/DPD",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("MapaMensal.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Arquivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("DataEntrega")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<decimal>("HorasGastas")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("mapa_tarefas", (string)null);
                });

            modelBuilder.Entity("MapaMensal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("mapa_users", (string)null);
                });

            modelBuilder.Entity("MapaMensal.Models.WorkDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Mark")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Date")
                        .IsUnique();

                    b.ToTable("mapa_workdays", (string)null);
                });

            modelBuilder.Entity("MapaMensal.Models.Compromisso", b =>
                {
                    b.HasOne("MapaMensal.Models.CategoriaCompromisso", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("MapaMensal.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("Categoria");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MapaMensal.Models.CompromissoParticipante", b =>
                {
                    b.HasOne("MapaMensal.Models.Compromisso", null)
                        .WithMany("Participantes")
                        .HasForeignKey("CompromissoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MapaMensal.Models.Tarefa", b =>
                {
                    b.HasOne("MapaMensal.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MapaMensal.Models.WorkDay", b =>
                {
                    b.HasOne("MapaMensal.Models.Project", "Project")
                        .WithMany("WorkDays")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MapaMensal.Models.Compromisso", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("MapaMensal.Models.Project", b =>
                {
                    b.Navigation("WorkDays");
                });
#pragma warning restore 612, 618
        }
    }
}
