export interface Pais {
  nome: string;
  codigo: string; // ISO 3166-1 alpha-2
  prefixo: string; // +351
  bandeira: string; // emoji
}

export const PAISES: Pais[] = [
  { nome: 'Portugal', codigo: 'PT', prefixo: '+351', bandeira: '🇵🇹' },
  { nome: 'Brasil', codigo: 'BR', prefixo: '+55', bandeira: '🇧🇷' },
  { nome: 'Angola', codigo: 'AO', prefixo: '+244', bandeira: '🇦🇴' },
  { nome: 'Moçambique', codigo: 'MZ', prefixo: '+258', bandeira: '🇲🇿' },
  { nome: 'Cabo Verde', codigo: 'CV', prefixo: '+238', bandeira: '🇨🇻' },
  { nome: 'Espanha', codigo: 'ES', prefixo: '+34', bandeira: '🇪🇸' },
  { nome: 'França', codigo: 'FR', prefixo: '+33', bandeira: '🇫🇷' },
  { nome: 'Alemanha', codigo: 'DE', prefixo: '+49', bandeira: '🇩🇪' },
  { nome: 'Reino Unido', codigo: 'GB', prefixo: '+44', bandeira: '🇬🇧' },
  { nome: 'Itália', codigo: 'IT', prefixo: '+39', bandeira: '🇮🇹' },
  { nome: 'Países Baixos', codigo: 'NL', prefixo: '+31', bandeira: '🇳🇱' },
  { nome: 'Bélgica', codigo: 'BE', prefixo: '+32', bandeira: '🇧🇪' },
  { nome: 'Suíça', codigo: 'CH', prefixo: '+41', bandeira: '🇨🇭' },
  { nome: 'Luxemburgo', codigo: 'LU', prefixo: '+352', bandeira: '🇱🇺' },
  { nome: 'Áustria', codigo: 'AT', prefixo: '+43', bandeira: '🇦🇹' },
  { nome: 'Suécia', codigo: 'SE', prefixo: '+46', bandeira: '🇸🇪' },
  { nome: 'Noruega', codigo: 'NO', prefixo: '+47', bandeira: '🇳🇴' },
  { nome: 'Dinamarca', codigo: 'DK', prefixo: '+45', bandeira: '🇩🇰' },
  { nome: 'Finlândia', codigo: 'FI', prefixo: '+358', bandeira: '🇫🇮' },
  { nome: 'Irlanda', codigo: 'IE', prefixo: '+353', bandeira: '🇮🇪' },
  { nome: 'Polónia', codigo: 'PL', prefixo: '+48', bandeira: '🇵🇱' },
  { nome: 'República Checa', codigo: 'CZ', prefixo: '+420', bandeira: '🇨🇿' },
  { nome: 'Hungria', codigo: 'HU', prefixo: '+36', bandeira: '🇭🇺' },
  { nome: 'Roménia', codigo: 'RO', prefixo: '+40', bandeira: '🇷🇴' },
  { nome: 'Bulgária', codigo: 'BG', prefixo: '+359', bandeira: '🇧🇬' },
  { nome: 'Grécia', codigo: 'GR', prefixo: '+30', bandeira: '🇬🇷' },
  { nome: 'Estados Unidos', codigo: 'US', prefixo: '+1', bandeira: '🇺🇸' },
  { nome: 'Canadá', codigo: 'CA', prefixo: '+1', bandeira: '🇨🇦' },
  { nome: 'México', codigo: 'MX', prefixo: '+52', bandeira: '🇲🇽' },
  { nome: 'Argentina', codigo: 'AR', prefixo: '+54', bandeira: '🇦🇷' },
  { nome: 'Chile', codigo: 'CL', prefixo: '+56', bandeira: '🇨🇱' },
  { nome: 'Colômbia', codigo: 'CO', prefixo: '+57', bandeira: '🇨🇴' },
  { nome: 'Peru', codigo: 'PE', prefixo: '+51', bandeira: '🇵🇪' },
  { nome: 'Venezuela', codigo: 'VE', prefixo: '+58', bandeira: '🇻🇪' },
  { nome: 'Uruguai', codigo: 'UY', prefixo: '+598', bandeira: '🇺🇾' },
  { nome: 'Paraguai', codigo: 'PY', prefixo: '+595', bandeira: '🇵🇾' },
  { nome: 'Bolívia', codigo: 'BO', prefixo: '+591', bandeira: '🇧🇴' },
  { nome: 'Equador', codigo: 'EC', prefixo: '+593', bandeira: '🇪🇨' },
  { nome: 'China', codigo: 'CN', prefixo: '+86', bandeira: '🇨🇳' },
  { nome: 'Japão', codigo: 'JP', prefixo: '+81', bandeira: '🇯🇵' },
  { nome: 'Coreia do Sul', codigo: 'KR', prefixo: '+82', bandeira: '🇰🇷' },
  { nome: 'Índia', codigo: 'IN', prefixo: '+91', bandeira: '🇮🇳' },
  { nome: 'Austrália', codigo: 'AU', prefixo: '+61', bandeira: '🇦🇺' },
  { nome: 'Nova Zelândia', codigo: 'NZ', prefixo: '+64', bandeira: '🇳🇿' },
  { nome: 'África do Sul', codigo: 'ZA', prefixo: '+27', bandeira: '🇿🇦' },
  { nome: 'Nigéria', codigo: 'NG', prefixo: '+234', bandeira: '🇳🇬' },
  { nome: 'Quénia', codigo: 'KE', prefixo: '+254', bandeira: '🇰🇪' },
  { nome: 'Marrocos', codigo: 'MA', prefixo: '+212', bandeira: '🇲🇦' },
  { nome: 'Guiné-Bissau', codigo: 'GW', prefixo: '+245', bandeira: '🇬🇼' },
  { nome: 'São Tomé e Príncipe', codigo: 'ST', prefixo: '+239', bandeira: '🇸🇹' },
];
